language: node_js
sudo: false
node_js:
- 8
- 6
cache:
  directories:
  - node_modules
after_success:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in travis-ci repo settings
  on:
    branch: master
